package mock

import (
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/gone-io/gonectr/utils"

	"errors"

	"github.com/spf13/cobra"
)

var scanDir string
var scanFile []string
var packageName string
var destinationDir string
var goneVersion string

func init() {
	Command.Flags().StringVarP(&scanDir, "scan-dir", "s", "", "scan dirs, for example: `-s file1 -s file2`")
	Command.Flags().StringArrayVarP(&scanFile, "scan-file", "f", []string{}, "scan files, for example: `-f dir1 -f dir2`")
	Command.Flags().StringVarP(&packageName, "package", "p", "", "package name for mock code")
	Command.Flags().StringVarP(&destinationDir, "destination", "d", "", "destination dir")
	Command.Flags().StringVarP(&goneVersion, "version", "v", "", "gone version")
}

var Command = &cobra.Command{
	Use:   "mock",
	Short: "generate mock goner code for interface",
	RunE: func(cmd *cobra.Command, args []string) error {
		if scanDir == "" && scanFile == nil {
			return errors.New("scan file or scan directory, at least one must be specified")
		}

		if packageName == "" {
			return errors.New("package name is required")
		}

		if destinationDir == "" {
			destinationDir = path.Join(scanDir, packageName)
		}

		err := os.MkdirAll(destinationDir, os.ModePerm)
		if err != nil {
			return err
		}

		var mockedStructs []string

		var genCode = func(theFilepath string) error {
			if !strings.HasSuffix(theFilepath, "gone.go") && strings.HasSuffix(theFilepath, ".go") {
				code, err := GenMockCode(theFilepath, packageName)
				if err != nil {
					return err
				}

				filename := filepath.Base(theFilepath)

				newFilepath := path.Join(destinationDir, fmt.Sprintf("%s.gone.go", strings.TrimSuffix(filename, ".go")))

				code = AddGoneCode(code)
				mocked := GetMockedInterface(code)
				mockedStructs = append(mockedStructs, mocked...)

				if len(mocked) > 0 {
					return os.WriteFile(newFilepath, []byte(code), 0644)
				}
			}
			return nil
		}

		if scanDir != "" {
			// 使用 filepath.Walk 递归扫描目录
			err = filepath.Walk(scanDir, func(theFilepath string, info os.FileInfo, err error) error {
				if err != nil {
					return err
				}

				// 检查是否是文件（排除目录）
				if !info.IsDir() {
					return genCode(theFilepath)
				}
				return nil
			})
			if err != nil {
				return err
			}
		}

		for _, f := range scanFile {
			err := genCode(f)
			if err != nil {
				return err
			}
		}

		priestCode := GenMockPriestCode(mockedStructs, packageName)

		return os.WriteFile(path.Join(destinationDir, "load.gone.go"), []byte(priestCode), 0644)
	},
}

func GenMockCode(source string, packageName string) (code string, err error) {
	cmd := exec.Command("mockgen",
		fmt.Sprintf("-source=%s", source),
		fmt.Sprintf("-package=%s", packageName),
		"-write_command_comment=false",
		"-write_package_comment=false",
	)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", err
	}
	return string(output), nil
}

const mockGneTpl = "// Code generated by MockGen. DO NOT EDIT."

func getGoneVersionFromModuleFile() string {
	if goneVersion == "" {
		goneVersion = utils.GetGoneVersionFromModuleFile([]string{scanDir}, scanFile)
	}
	return goneVersion
}

func AddGoneCode(code string) string {
	code = strings.Replace(code, mockGneTpl, utils.GenerateBy, 1)

	goneVersion = getGoneVersionFromModuleFile()

	versionSuffix := ""
	if goneVersion != "v1" {
		versionSuffix = fmt.Sprintf("/%s", goneVersion)
	}

	goneImport := fmt.Sprintf("import (\n\t\"github.com/gone-io/gone%s\"", versionSuffix)

	code = strings.Replace(code, "import (", goneImport, 1)
	return strings.Replace(code, "isgomock struct{}", "isgomock struct{}\n\tgone.Flag", -1)
}

var re = regexp.MustCompile(`(?s)type (\S*?) struct[^}]+?isgomock[^}]+?}`)

func GetMockedInterface(code string) (list []string) {
	//	使用正则表达式提取
	match := re.FindAllStringSubmatch(code, -1)

	for _, m := range match {
		list = append(list, m[1])
	}

	return list
}

// priest.gone.go
var priestTpl = utils.GenerateBy + `

package %s

import (
	"github.com/gone-io/gone"
	gomock "go.uber.org/mock/gomock"
)

func MockPriest(cemetery gone.Cemetery, ctrl *gomock.Controller) {
%s
}
`

var v2LoaderTpl = utils.GenerateBy + `

package %s

import (
	"github.com/gone-io/gone/%s"
	gomock "go.uber.org/mock/gomock"
)

func MockLoader(loader gone.Loader, ctrl *gomock.Controller) {
%s
}
`

func GenMockPriestCode(mockedStructs []string, packageName string) (code string) {
	getGoneVersionFromModuleFile()
	var needBury []string
	for _, mocked := range mockedStructs {
		if strings.Contains(mocked, "[") {
			continue
		}

		if goneVersion == "v1" {
			needBury = append(needBury, fmt.Sprintf("\tcemetery.Bury(New%s(ctrl))", mocked))
		} else {
			needBury = append(needBury, fmt.Sprintf("\t_ = loader.Load(New%s(ctrl))", mocked))
		}
	}

	if goneVersion == "v1" {
		return fmt.Sprintf(priestTpl, packageName, strings.Join(needBury, "\n"))
	} else {
		return fmt.Sprintf(v2LoaderTpl, packageName, goneVersion, strings.Join(needBury, "\n"))
	}
}
